//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.01 at 12:03:23 PM PDT 
//


package org.mash.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * org.testfw.xml package. <p>An ObjectFactory allows you to programatically construct new instances of the Java
 * representation for XML content. The Java representation of XML content can consist of schema derived interfaces and
 * classes representing the binding of schema type definitions, element declarations and model groups.  Factory methods
 * for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory
{


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * org.testfw.xml
     */
    public ObjectFactory()
    {
    }

    /**
     * Create an instance of {@link Configuration }
     */
    public Configuration createConfiguration()
    {
        return new Configuration();
    }

    /**
     * Create an instance of {@link Parameter }
     */
    public Parameter createParameter()
    {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Replace }
     */
    public Replace createReplace()
    {
        return new Replace();
    }

    public Date createDate()
    {
        return new Date();
    }

    /**
     * Create an instance of {@link Setup }
     */
    public Setup createSetup()
    {
        return new Setup();
    }

    /**
     * Create an instance of {@link Script }
     */
    public Script createTest()
    {
        return new Script();
    }

    /**
     * Create an instance of {@link Verify }
     */
    public Verify createVerify()
    {
        return new Verify();
    }

    public Teardown createTeardown()
    {
        return new Teardown();
    }

    /**
     * Create an instance of {@link Parallel }
     */
    public Parallel createParallel()
    {
        return new Parallel();
    }

    /**
     * Create an instance of {@link Run }
     */
    public Run createRun()
    {
        return new Run();
    }

    /**
     * Create an instance of {@link Suite }
     */
    public Suite createSuite()
    {
        return new Suite();
    }

}
